[package]
name = "goodschema"
version = "0.0.0"
edition = "2021"
description = "generate structs and validators from json schema"
license = "ISC"
authors = ["Elmer Bulthuis"]
homepage = "https://www.goodschema.org"
keywords = ["good", "json", "schema"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
serde = "1.0.158"
serde_json = "1.0.94"
